export * from "./getTextNodesBetween";
export * from "./highlightRange";
export * from "./getHighlightRanges";
export * from "./unhighlightAll";
export * from "./unwrap";
export * from "./clearSelection";
export * from "./highlight";
export * from "./utils";
export * from "./restoreHighlights";
